### ISSUE TITLE
Compilation error in SocketRocket in Xcode 14.3

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1591]
[This line](https://github.com/ably/ably-cocoa/blob/cfa0ad767eecb25d5226e692c92d5ae978928ae1/Source/SocketRocket/NSURLRequest%2BARTSRWebSocket.m#LL16C41-L16C41) of SocketRocket code is giving an error "A function declaration without a prototype is deprecated in all versions of C" in Xcode 14.3.

**Comment by l-szyszkowski** [comment]
> [This line](https://github.com/ably/ably-cocoa/blob/cfa0ad767eecb25d5226e692c92d5ae978928ae1/Source/SocketRocket/NSURLRequest%2BARTSRWebSocket.m#LL16C41-L16C41) of SocketRocket code is giving an error "A function declaration without a prototype is deprecated in all versions of C" in Xcode 14.3.

I assume it's not just one line, I'm facing the same error when I'm trying to build ably framework with Xcode 14.3
<img width="1235" alt="CleanShot 2023-04-13 at 13 48 39@2x" src="https://user-images.githubusercontent.com/130652619/231749564-806974a9-b2fe-42dd-a2c8-77efeff26e59.png">
[possible solution](https://stackoverflow.com/questions/75943541/a-function-declaration-without-a-prototype-is-deprecated-in-all-versions-of-c#comment133948828_75943541)

**Comment by lawrence-forooghian** [comment]
> Greetings,
> I'm also facing an issue "**dyld: Library not loaded: @rpath/Ably.framework/Ably**" and **Reason: image not found**
> This happens when running the app either on the Simulator or a Real device.
> Xcode version: 14.3.
> I really appreciate your support.
> Thanks in advance

Hi @sAurangzaib — would you be able to raise a separate issue for this, please?
