### ISSUE TITLE
1.2.34 and newer are incompatible with ably-asset-tracking-swift

### ISSUE THREAD

**Issue by p0wl** [ably/ably-cocoa#2003]
### Which version of the Ably SDK are you using? 
`1.2.34`

### On which platform does the issue happen? 
`iOS17`

### Which version of Xcode are you using? 
`Xcode 15.3`

### What did you do?
After updating the ably-cocoa package to 1.2.35 or 1.2.34, we cannot build our iOS App anymore, as it is using the [ably-asset-tracking-swift SDK](https://github.com/ably/ably-asset-tracking-swift) as well and ably-asset-tracking-swift has not been updated to be compatible with the changes that were introduced in https://github.com/ably/ably-cocoa/pull/1995

The build fails with:
```
Failed to execute Step: command failed with exit status 65 (xcodebuild "-project" "/Users/vagrant/git/Project.xcodeproj" "-scheme" "Project Development" "test" "-destination" "id=..." "-resultBundlePath" "/var/folders/7l/.../T/XCUITestOutput236194744/Test-Project Development.xcresult" "-xcconfig" "/var/folders/7l/.../T/.../temp.xcconfig"): /Users/vagrant/Library/Developer/Xcode/DerivedData/Project-.../SourcePackages/checkouts/ably-asset-tracking-swift/Sources/AblyAssetTrackingInternal/AblyWrapper/SDK/AblyCocoaSDK.swift:41:56: error: cannot convert value of type 'any ARTRealtimePresenceProtocol' to expected argument type 'ARTRealtimePresence' (exit code: 1)
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5186) by [Unito](https://www.unito.io)

**Comment by ttypic** [comment]
Hi @p0wl,

Thank you for reporting this! We are investigating this internally and will get back to you soon.

**Comment by p0wl** [comment]
Thank you for the fast fix! We'll update to 1.2.37 and report back if it doesn't work :)
