### ISSUE TITLE
TypingOperationQueue.swift fails to compile on Xcode 26.4 / Swift 6.2 due to actor-isolation error

### ISSUE THREAD

**Issue by sethdeckard** [ably/ably-cocoa#2202]
Building `ably-chat-swift` with Xcode 26.4 / Swift 6.2 fails in `Sources/AblyChat/TypingOperationQueue.swift` because of stricter actor-isolation/sendability
  checking.

  ### Compiler error

  ```text
  TypingOperationQueue.swift:96:38: error: sending 'pendingRequest' risks causing data races
  await pendingRequest.performOperation()
        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

  note: sending main actor-isolated 'pendingRequest' to nonisolated instance method 'performOperation()' risks causing data races between nonisolated and main
  actor-isolated uses
```

  ### Code

  TypingOperationQueue is @MainActor, and the failure happens in didFinishExecutingOperation() when a pending request is executed inside a Task:

```swift
@MainActor
internal class TypingOperationQueue<Failure: Error> {
  private struct Request {
    func performOperation() async {
      let result = await operation()
        complete(with: result)
    }

    func complete(with result: Result<Void, Failure>) {
      continuation.resume(returning: result)
    }
  }

  private func didFinishExecutingOperation() {
    if let pendingRequest {
      state = .executing(pendingRequest: nil)
        Task {
          await pendingRequest.performOperation()
            didFinishExecutingOperation()
        }
    } else {
      state = .idle
    }
  }
}
```

  ### What fixed it locally

  We were able to get the package compiling by explicitly marking the nested Request methods as @MainActor and making the task main-actor isolated as well:

```swift
@MainActor
func performOperation() async { ... }

@MainActor
func complete(with result: Result<Void, Failure>) { ... }

Task { @MainActor in
    await pendingRequest.performOperation()
    didFinishExecutingOperation()
}
```

  ### Environment

  - Xcode 26.4
  - Swift 6.2
  - iOS simulator build
  - Reproduced with ably-chat-swift 1.2.0

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5702) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Thanks for reporting this, @sethdeckard. I've got a fix for it in https://github.com/ably/ably-chat-swift/pull/482; once it's released I'll let you know.

**Comment by lawrence-forooghian** [comment]
This is fixed in version 1.2.1.
